server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
      include: '*'
  base-path: /actuator
  health:
    sensitive: false
info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@